### ISSUE TITLE
Add Windows Support.

### ISSUE THREAD

**Issue by aadrian** [babashka/babashka.process#15]
Hi,

Please add Windows support too.

e.g.  on Windows there's Bash (from Git) , "lein" https://chocolatey.org/packages/Lein  ( and "boot" https://chocolatey.org/packages/boot-clj ) but there's no "clojure" (since the clojure/tools seem to be mostly a "hombrew" only solution now :( ) .

So:
```shell
export BABASHKA_CLASSPATH=$(clojure -Sdeps '{:deps {babashka/babashka.process {:sha "6c348b5213c0c77ebbdfcf2f5da71da04afee377" :git/url "https://github.com/babashka/babashka.process"}}}' -Spath)
``` 
won't work

Thanks in advance.

**Comment by borkdude** [comment]
@aadrian Hi, `clojure` does exist on Windows, but only works from Powershell. It can be installed with scoop with is similar to brew:

https://github.com/littleli/scoop-clojure

That scoop also has deps.clj, which is similar to clojure, but also works in cmd.exe.

Btw, the scoop also has some of my other tools: babashka and clj-kondo, which may be worth looking at.

**Comment by aadrian** [comment]
>  clojure does exist on Windows, but only works from Powershell

@borkdude unfortunately in most corporate environments Powershell is blocked/limited by security policies :( 


> Btw, the scoop also has some of my other tools: babashka and clj-kondo

Great, but Chocolatey https://chocolatey.org/ is the more widely used windows dependency tool in corporate environments, since it also has a GUI and "commercial support" (so that the management is happy too).

Clojure until 1.6 used to work on Windows from https://chocolatey.org/packages/clojure too, without problems. 
Clojure Tools broke everything and it seems that OSX ( Homebew ) is the only "first class citizen" now.

**Comment by borkdude** [comment]
@aadrian If powershell is a problem, you can download the deps.clj binary (deps.exe) directly from Github releases and place it on your path: https://github.com/borkdude/deps.clj/releases. There is no additional install required, except Java. The tool will download a .jar file on initial usage which is the same .jar file used by the official Clojure tool.

**Comment by aadrian** [comment]
>  If powershell is a problem, you can download the deps.clj binary (deps.exe) directly from Github releases and place it on your path: https://github.com/borkdude/deps.clj/releases. There is no additional install required, except Java. The tool will download a .jar file on initial usage which is the same .jar file used by the official Clojure tool.

@borkdude This sounds great! Thank you.
